codecov:
  branch: main # set new Default branch

ai_pr_review:
  enabled: true

coverage:
  precision: 2
  round: down
  range: '60...85'

  status:
    project: yes
    patch: yes
    changes: no


comment:
  layout: 'reach, diff, flags, files, components, footer'
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - ./src/**/*.stories.js
  - ./src/**/*.stories.jsx
  - ./src/**/*.stories.ts
  - ./src/**/*.stories.tsx
  - ./src/setupTests.ts
  - ./src/setupProxy.js
  - ./src/reportWebVitals.ts
  - ./scripts/*
  - ./public/*
  - ./config/*
  - ./.github/*
  - ./src/index.tsx
  - ./src/sentry.ts
  - ./src/mocks/*.js
  - ./src/**/flags/**/*.js
  - ./src/**/mocks.js

profiling:
  critical_files_paths:
    - ./src/components/*