codecov:
  branch: main # set new Default branch

ai_pr_review:
  enabled: true

coverage:
  precision: 2
  round: down
  range: '60...85'

  status:
    project: yes
    patch: yes
    changes: no


comment:
  layout: 'reach, diff, flags, files, components, footer'
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  after_n_builds: 6

ignore:
  - ./src/**/*.stories.js
  - ./src/**/*.stories.jsx
  - ./src/**/*.stories.ts
  - ./src/**/*.stories.tsx
  - ./src/setupTests.js
  - ./src/setupProxy.js
  - ./src/reportWebVitals.js
  - ./scripts/*
  - ./src/index.js
  - ./src/sentry.ts
  - ./src/mocks/*.js
  - ./src/**/flags/**/*.js
  - ./src/**/mocks.js
  - ./src/pages/RepoPage/repo-jest-setup.js
  - ./src/ui/SunburstChart/*.jsx
  - ./src/ui/SunburstChart/*.js